# Generated by Django 3.0 on 2019-12-23 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.TextField(verbose_name='歌手名稱')),
                ('picture', models.ImageField(upload_to='', verbose_name='歌手照片')),
                ('introduce', models.TextField(verbose_name='歌手介紹')),
            ],
            options={
                'verbose_name': '歌手資訊',
                'verbose_name_plural': '歌手資訊',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10, verbose_name='熱門程度')),
            ],
            options={
                'verbose_name': '類別',
                'verbose_name_plural': '類別',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10, verbose_name='曲風名稱')),
                ('Description', models.TextField(verbose_name='曲風介紹')),
            ],
            options={
                'verbose_name': '曲風名稱',
                'verbose_name_plural': '曲風名稱',
            },
        ),
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50, verbose_name='歌曲名稱')),
                ('album_name', models.CharField(max_length=50, verbose_name='專輯名稱')),
                ('artwork', models.ImageField(upload_to='', verbose_name='專輯封面')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('lycris', models.TextField(verbose_name='歌詞')),
                ('story', models.TextField(verbose_name='故事')),
                ('mv', models.URLField(verbose_name='MV')),
                ('artist', models.ManyToManyField(to='routes.Artist', verbose_name='歌手')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Category', verbose_name='分類')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Style', verbose_name='曲風')),
            ],
            options={
                'verbose_name': '歌曲資訊',
                'verbose_name_plural': '歌曲資訊',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Category', verbose_name='歌曲'),
        ),
    ]
