# Generated by Django 3.0 on 2019-12-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='song',
        ),
    ]
